### ISSUE TITLE
Wagtail 2 compatible release

### ISSUE THREAD

**Issue by tomdyson** [wagtail/wagtail-bakery#30]
Could you please release a Wagtail 2.x-compatible version? It looks like most of the work has been merged. Thanks!

**Comment by loicteixeira** [comment]
Changes for the package have indeed been merged but the tests fail because the imports haven't been updated there. I'm happy to submit a PR @robmoorman but I would need to know whether you would rather have:
- The tests passing for Wagtail 2.0 and not test previous versions
- The tests to pass with all versions of Wagtail (similarly to what we've done with [wagtail-django-recaptcha](https://github.com/springload/wagtail-django-recaptcha)).

**Comment by ninepints** [comment]
Based on https://github.com/moorinteractive/wagtail-bakery/commit/40d388a16eed81434c8f6bed59a84b411d802024 I went ahead with the maximum-compatibility approach: https://github.com/moorinteractive/wagtail-bakery/pull/32

**Comment by loicteixeira** [comment]
Version `0.3.0` has been released to PyPI, thanks to the contributions of @BertrandBordage, @robmoorman, @stuaxo and @falseperfection 🎉
